# Generated by Django 4.2.20 on 2025-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='atores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='avaliacao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='cartaz',
            field=models.ImageField(blank=True, null=True, upload_to='filmes/cartazes/'),
        ),
        migrations.AddField(
            model_name='filme',
            name='citacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='link_streaming',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='orcamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='premios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='receita',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
